<?php

namespace AppBundle\Repository;

/**
 * demotableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class demotableRepository extends \Doctrine\ORM\EntityRepository
{
}
