<?php

namespace AppBundle\Repository;

/**
 * sometabeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sometabeRepository extends \Doctrine\ORM\EntityRepository
{
}
