<?php

namespace AppBundle\Repository;

/**
 * sometableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sometableRepository extends \Doctrine\ORM\EntityRepository
{
}
