<?php

namespace AppBundle\Repository;

/**
 * vikRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vikRepository extends \Doctrine\ORM\EntityRepository
{
}
