# # Learn more about services, parameters and containers at
# # http://symfony.com/doc/current/book/service_container.html
# parameters:
#     my_service_connection: default

# # services:
# #     creator_service:
# #         class: AppBundle\Controller\creatorController
# #         arguments: []
# services:
# toolbox_service: 
#     class:AppBundle\Toolbox\StringToolbox
#     arguments:[@doctrine.dbal.%my_service_connection%_connection]

